# day 3 | 250903



In [2]:
import numpy as np
import pandas as pd

## strings

In [3]:
x = 'JD did his homework.'

In [4]:
x

'JD did his homework.'

In [19]:
x[-4:-1]

'ork'

## lists

In [20]:
y = [4, 5, 6.0, 'dog', 5+1j]

In [21]:
y

[4, 5, 6.0, 'dog', (5+1j)]

In [28]:
y[2]

6.0

In [27]:
y[2:3]

[6.0]

In [29]:
y

[4, 5, 6.0, 'dog', (5+1j)]

In [30]:
y.pop(3)

'dog'

In [31]:
y

[4, 5, 6.0, (5+1j)]

In [32]:
z = [3.4, 5, 12.1, 15]

In [33]:
a = y + z

In [34]:
a

[4, 5, 6.0, (5+1j), 3.4, 5, 12.1, 15]

In [35]:
b = y*z

TypeError: can't multiply sequence by non-int of type 'list'

In [36]:
a - 1

TypeError: unsupported operand type(s) for -: 'list' and 'int'

In [37]:
c = np.array([1, 2, 5.0, 6.33333, 12])

In [38]:
c

array([ 1.     ,  2.     ,  5.     ,  6.33333, 12.     ])

In [42]:
c.dtype

dtype('float64')

In [43]:
c[0]

1.0

In [45]:
c[2:4]

array([5.     , 6.33333])

In [46]:
y+1

TypeError: can only concatenate list (not "int") to list

In [47]:
c+1

array([ 2.     ,  3.     ,  6.     ,  7.33333, 13.     ])